fixup! Edit Pipeline Trigger

diff --git a/.pipelines/templates/rename-dockerfile-references.steps.yaml b/.pipelines/templates/rename-dockerfile-references.steps.yaml
--- a/.pipelines/templates/rename-dockerfile-references.steps.yaml
+++ b/.pipelines/templates/rename-dockerfile-references.steps.yaml
@@ -39,6 +39,9 @@
 #     references to the old dockerfile name. Replce will default to $target_path 
 #     if not provided.
 #
+#   dockerfile_cleanup (boolean|default) - If this is set to true, this module
+#     will remove any dockerfiles that are unrelated to the $target_dockerfile.
+#
 #   topic (string|default) - Appends a provided topic string to the display 
 #     name. Need not be unique. Defaults to empty string.
 #
@@ -71,6 +74,10 @@ parameters:
   type: string
   default: ''
 
+- name: dockerfile_cleanup
+  type: boolean
+  default: true
+
 - name: topic
   type: string
   default: ''
@@ -95,10 +102,11 @@ steps:
   ${{ else }}:
     displayName: "Create OneBranch Docker Workspace - ${{ parameters.topic }}"
 
+
 - bash: |
     set -e; [[ -n $SYSTEM_DEBUG ]] && [[ $SYSTEM_DEBUG =~ ^[T|t]rue$ ]] && set -x
 
-    echo >&2 "##[info]Renaming source dockerfile ('$TARGET_DOCKERFILE') to desired name ('$TARGET_DOCKERFILE')."
+    echo >&2 "##[info]Renaming source dockerfile ('$SOURCE_DOCKERFILE') to desired name ('$TARGET_DOCKERFILE')."
     mv "$SOURCE_REL_PATH"/"$SOURCE_DOCKERFILE" "$TARGET_REL_PATH"/"$TARGET_DOCKERFILE"
   workingDirectory: $(ACR_DIR)
   env: 
@@ -110,6 +118,7 @@ steps:
     displayName: "Move Dockerfile to OneBranch Approved Naming Format - ${{ parameters.topic }}"
   ${{ else }}:
     displayName: "Move Dockerfile to OneBranch Approved Naming Format"
+
 
 - bash: |
     set -e; [[ -n $SYSTEM_DEBUG ]] && [[ $SYSTEM_DEBUG =~ ^[T|t]rue$ ]] && set -x
@@ -134,12 +143,14 @@ steps:
   ${{ else }}:
     displayName: "Replace References to Updated Dockerfile"
 
+
 - bash: |
     set -e; [[ -n $SYSTEM_DEBUG ]] && [[ $SYSTEM_DEBUG =~ ^[T|t]rue$ ]] && set -x
 
     echo >&2 "##[info]Deleting top-level dockerfiles that are -not- the target ('$TARGET_DOCKERFILE')."
     find "$TARGET_REL_PATH" -maxdepth 1 -type f -name '*Dockerfile' ! -wholename "$TARGET_REL_PATH"/"$TARGET_DOCKERFILE" -delete
   workingDirectory: $(ACR_DIR)
+  condition: and(succeeded(), '${{ parameters.dockerfile_cleanup }}')
   env: 
     SOURCE_REL_PATH: ${{ parameters.source_path }}
     TARGET_REL_PATH: ${{ parameters.target_path }}
