fixup! Edit Pipeline Trigger

diff --git a/.pipelines/templates/rename-dockerfile-references.steps.yaml b/.pipelines/templates/rename-dockerfile-references.steps.yaml
--- a/.pipelines/templates/rename-dockerfile-references.steps.yaml
+++ b/.pipelines/templates/rename-dockerfile-references.steps.yaml
@@ -86,13 +86,15 @@ parameters:
 steps:
 
 - bash: |
-    set -e; [[ -n $SYSTEM_DEBUG ]] && [[ $SYSTEM_DEBUG =~ ^[T|t]rue$ ]] && set -x
+    set -e; # - Not set here because '-d' will cause non-zero exit break.
+    [[ -n $SYSTEM_DEBUG ]] && [[ $SYSTEM_DEBUG =~ ^[T|t]rue$ ]] && set -x
 
-    trap 'echo "##[info]Directory ('$TARGET_REL_PATH') already exists. Preventing error."; exit 0' ERR
     if ! [[ -d "$TARGET_REL_PATH" ]]; then
       echo >&2 "##[info]Target path ('$TARGET_REL_PATH') does not exist, copying source contents to new folder."
       mkdir -p "$TARGET_REL_PATH"
       cp -r "$SOURCE_REL_PATH" "$TARGET_REL_PATH"
+    else
+      echo >&2 "##[info]Target path ('$TARGET_REL_PATH') exits. Nothing to do."
     fi
   workingDirectory: $(ACR_DIR)
   env: 
